# NOTE: Generated By HttpRunner v3.1.3
# FROM: testcases/no_backend_data_request.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.get_login_session_test import TestCaseGetLoginSession as GetLoginSession


class TestCaseNoBackendDataRequest(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters({"username-password": "${parameterize(testcases/account.csv)}"}),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("no_backend_data_request").base_url("${base_url()}").verify(False)

    teststeps = [
        Step(
            RunTestCase("get login session")
            .call(GetLoginSession)
            .export(*["login_session"])
        ),
        Step(
            RunRequest("get vote display")
            .get("/voter/display")
            .with_headers(**{"Cookie": "SESSION=$login_session"})
            .extract()
            .with_jmespath('headers."X-CSRF-TOKEN"', "csrf_token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", "0")
            .assert_equal("body.data", [])
        ),
    ]


if __name__ == "__main__":
    TestCaseNoBackendDataRequest().test_start()
